version: "3.8"

services:
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      MONGO_URI: "mongodb://vericart_user:securepassword123@mongodb:27017/vericart?authSource=vericart"
      JWT_SECRET: "your_jwt_secret"
      RABBITMQ_HOST: "rabbitmq"
    volumes:
      - .:/app
    restart: always

  mongodb:
    image: mongo:latest
    container_name: vericart-mongodb-1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping').ok"]
      interval: 20s
      timeout: 20s
      retries: 5
    restart: always

rabbitmq:
  image: "rabbitmq:3-management"
  container_name: vericart-rabbitmq-1
  ports:
    - "5673:5672"      # Changed AMQP port
    - "15673:15672"    # Changed management UI port
  environment:
    RABBITMQ_DEFAULT_USER: guest
    RABBITMQ_DEFAULT_PASS: guest
  healthcheck:
    test: ["CMD", "rabbitmq-diagnostics", "check_running"]
    interval: 20s
    timeout: 20s
    retries: 5
  restart: always


volumes:
  mongodb_data:
    external: true
