version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      MONGO_URI: "mongodb://mongodb:27017/vericart"
      JWT_SECRET: "your_jwt_secret"
    volumes:
      - .:/app
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
